[file]
directory = "~/Documents/dn"
segment_order = ["identifier", "signature", "title", "keywords", "extension"] # These are not optional, you must specify each segment.
default_extension = "txt"
regenerate_identifier = false
template_path = ""
illegal_characters = ['a', '!']

[frontmatter]
enabled = false
format = "text" # text, yaml, toml, org
time_style = "hour24" # or "hour12" or "none"
order = ["title", "date", "keywords", "identifier"] # These are all optional so you can leave some out?
