# SPDX-FileCopyrightText: 2024 Matthew Mark Ibbetson
# SPDX-FileContributor: Matthew Mark Ibbetson
#
# SPDX-License-Identifier: GPL-3.0-or-later

[file]
directory = "~/Documents/dn"
segment_order = [
    "identifier",
    "signature",
    "title",
    "keywords",
    "extension",
] # These are not optional, you must specify each segment.
default_extension = "txt"
regenerate_identifier = false
illegal_characters = [
    "[",
    "]",
    "{",
    "}",
    "(",
    ")",
    "!",
    "#",
    "$",
    "%",
    "^",
    "&",
    "*",
    "+",
    "'",
    "\\",
    "\"",
    "?",
    ",",
    "|",
    ";",
    ":",
    "~",
    "`",
    "‘",
    "’",
    "“",
    "”",
    "/",
    "*",
    " ",
    "@",
    "=",
    "-",
    "_",
    ".",
]
# template_path = "" # If you want to by default reuse a template for a diary workflow, for example.

[frontmatter]
enabled = false
format = "text" # text, yaml, toml, org
# time_style = "" # valid chrono datetime format string. If not provided, will default depending on frontmatter format.
order = [
    "title",
    "date",
    "keywords",
    "identifier",
] # These are all optional so you can leave some or all out
