[file]
directory = "~/Documents/dn"
segment_order = [
    "identifier",
    "signature",
    "title",
    "keywords",
    "extension",
]
default_extension = "txt"
regenerate_identifier = false
illegal_characters = [
    '[',
    ']',
    '{',
    '}',
    '(',
    ')',
    '!',
    '#',
    '$',
    '%',
    '^',
    '&',
    '*',
    '+',
    '\',
    '"',
    "'",
    '?',
    ',',
    '|',
    ';',
    ':',
    '~',
    '`',
    '‘',
    '’',
    '“',
    '”',
    '/',
    '*',
    ' ',
    '@',
    '=',
    '-',
    '_',
    '.',
]
# template_path = ""

[frontmatter]
enabled = false
format = "text"
# time_style = ""
order = [
    "title",
    "date",
    "keywords",
    "identifier",
]
