[file]
default_extension = "txt"
directory = "~/Documents/dn"
illegal_characters = [
    '[',
    ']',
    '{',
    '}',
    '(',
    ')',
    '!',
    '#',
    '$',
    '%',
    '^',
    '&',
    '*',
    '+',
    '\',
    '"',
    "'",
    '?',
    ',',
    '|',
    ';',
    ':',
    '~',
    '`',
    '‘',
    '’',
    '“',
    '”',
    '/',
    '*',
    ' ',
    '@',
    '=',
    '-',
    '_',
    '.',
]
regenerate_identifier = false
segment_order = ["identifier", "signature", "title", "keywords", "extension"]
# template_path = ""
